### ISSUE TITLE
C Wrapper or Calling from C with variadic

### ISSUE THREAD

**Issue by m-luu** [cppformat/cppformat#167]
Firstly, great lib! We have a mix of C and C++ code. While this has been extremely great to use in C++, I can't seem to make it work having written a C wrapper around my code that calls fmt::format(...). Is there a way to construct ArgList from variadic or for ftm::format to take va_list?

Ideally:
void c_writeLog(int i, ...) {
  va_list args,
  fmt::ArgList arglist(args);
  writeLog(arglist);
}

void writeLog(fmt::ArgList args) {
  std::string s = "blah {1}";
  fmt::format(s, args);
}
FMT_VARIADIC(void, writeLog);

**Comment by vitaut** [comment]
Unfortunately it is not possible to construct `ArgList` from `va_list` because the latter doesn't preserve argument types. C++ Format relies on overloading and, optionally, variadic templates to capture type information. These are not available in C, so I don't think it's possible to create a usable C interface to the library.
