### ISSUE TITLE
How do I print a bool?

### ISSUE THREAD

**Issue by gnzlbg** [cppformat/cppformat#170]
I would like to print a C++ bool, such that when it is true it outputs "true", and false outputs "false". I can workaround this with the ternary operator, but it shouldn't be necessary.

There doesn't seem to be anything about this in the [syntax docs](http://cppformat.github.io/latest/syntax.html).

**Comment by vitaut** [comment]
Thanks for the feedback. Currently `bool` is treated as an integer which might be somewhat confusing. I think it would be reasonable to change the default to the textual format and if anyone wants to print `bool` as a number they will still be able to use `d` or any other integer format specifier:

```c++
fmt::print("{}", true); // will print true (currently prints 1)
fmt::print("{:d}", true); // prints 1
```

This will be consistent with Python's behavior. What do you think?

**Comment by gnzlbg** [comment]
I was expecting to remain consistent with `std::cout` where `std::cout << true;` prints `1`. 

```c++
fmt::print("{}", true); // prints 1 (as it currently does)
fmt::print("{:boolalpha}", true); // prints true
```
where `boolalpha` (or a shorter name) is just a format specifier. 

I like Python's behavior tho, so it is just a tradeoff of "breaking" existing code vs doing the "nice" thing. There is no right solution.

As long as there is an easy way to do it I am happy.

**Comment by chipdude** [comment]
Unary + turns bool to int easily, so bool printing as true/false is the better default.

**Comment by vitaut** [comment]
@gnzlbg I thought about `b` too but, as you correctly pointed out, it is already used for binary and I'm a bit reluctant to add another specifier unless absolutely necessary. Since `fmt::format` is modeled after Python's `str.format`, I think it is reasonable to prefer consistency with the latter to IOStreams.

A more serious concern is breaking expectations of existing code, but this can be mitigated by a configuration option that returns the old behavior for projects that rely on it. In any case, since bool formatting is not documented at all, anyone who used it was using it at their own risk =).

@chipdude Thank you for the feedback too.

**Comment by gnzlbg** [comment]
Since the project follows semantic versioning, it actually suffices to bump
up the API version to break the API for old projects. Doing that for this
"small" change is overkill, but one does not have to do that now. Providing
a macro to switch the behavior should be enough. When more compelling
reasons to break the API appear one could deprecate it or something. It's
your library, touch decision.

**Comment by vitaut** [comment]
Fixed in https://github.com/cppformat/cppformat/commit/9d09214e7aefdf2daf529a91632488d17933811e. This will be in the next release (2.0) since there are other breaking changes that require major version change anyway.

**Comment by gnzlbg** [comment]
Thanks!
