### ISSUE TITLE
uint8_t formatted as a character by default

### ISSUE THREAD

**Issue by Nekotekina** [cppformat/cppformat#217]
Hi!

Was it indended that the value of `std::uint8_t` type becomes a character if formatted as `{}`? It was slightly confusing.

**Comment by vitaut** [comment]
Hi, @Nekotekina.

No, this is not intentional, but an unfortunate consequence of ``std::uint8_t`` being defined as ``unsigned char``. It might be worth changing the default format of ``unsigned char`` and ``signed char`` to numeric, but other potentially undesirable side-effects must be considered.

In the meantime you can format ``std::uint8_t`` using a numeric format specifier such as `d`:

```c++
  std::uint8_t u = 42;
  fmt::format("{:d}", u);
```
or promoting the argument to `int`:

```c++
  fmt::format("{}", +u);
```

**Comment by vitaut** [comment]
Fixed in https://github.com/cppformat/cppformat/commit/7c2497363773249217cf201f1dec708416fbc15a.

**Comment by Nekotekina** [comment]
Thanks!
