### ISSUE TITLE
visit_any_int incorrect signed long long casting

### ISSUE THREAD

**Issue by rglarix** [cppformat/cppformat#265]
Hi, I believe visit_any_int has an incorrect casting for the signed long long case.
Both branches of the if at line 329 of format.cc end up doing 
  arg_.long_long_value = static_cast < typename fmt::internal::MakeUnsigned < U>::Type>(value);

Perhaps the is_signed branch should do
        arg_.long_long_value = static_cast < long long>(static_cast < T>(value));
instead ?

**Comment by vitaut** [comment]
Thanks for reporting this, but the existing code looks correct to me. The branches differ in that the first assigns to `long_long_value` and the second to `ulong_long_value`. The cast to unsigned is used for consistency with glibc's printf as in:

```
std::printf("%lld", -42);  // prints "4294967254" in glibc
```
although it's not technically necessary because this is UB.

I've added a comment to clarify this in https://github.com/cppformat/cppformat/commit/ae6368c98566a29c73e3aa94d1742ccbaf3b6dce.

**Comment by rglarix** [comment]
First, many thanks for cppformat and your super-fast answer. *Thank you*, really.

Sorry to be a nuisance on a minor matter like this, but isn't this another instance of cppformat having better type information than C ?
As you said, this is undefined behavior, but cppformat can easily give a better answer by casting to the correct type, instead of unsigned.
Besides, while the current result is compatible with glibc, is different from Visual C++ 2013, which prints -4540733497999884330 (garbage) instead of -42.

**Comment by vitaut** [comment]
Fair enough. I've removed the conversion to an unsigned type in https://github.com/cppformat/cppformat/commit/7ee287d3d9e340737f3ad66292e7bc60a53b3053, so `fmt::printf` should now do the Right Thing, namely signed extend the argument of a smaller signed type:

```c++
  fmt::printf("%lld", -42); // prints -42
```

Thanks for reporting this and for the nice feedback.

**Comment by rglarix** [comment]
thank you
