### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by WscriChy** [cppformat/cppformat#287]
I am currently preparing freebsd port for cppformat. And have some issue with version 2.0.0, for example it does not install `format.cc` (what breaks header-only usage of the library), and no cmake config, as well as last fixes important for clang compiler (freebsd is clang-based system) and etc.

So I would like to know when do you plan to do next release, or can you make a new tag like 2.1.0, or 2.0.1. Because tracking hashes is a little bit messy, that is why I would like to have a tag. Thanks.

**Comment by vitaut** [comment]
Cool, thanks for working on this. I can make a minor 2.1 release some time next week with updated CMake files and, possibly, selected fixes from `master`. BTW which fixes you talking about? Version 2.0 has been tested with Clang (on OS X) so unless an old version of the compiler is used no fixes should be necessary. Most of the recent clang-related commits are only to silence warnings.

**Comment by WscriChy** [comment]
Good, thank you. Yes, I meant warnings, like #281. When you have `-Wall` and/or `-Wextra` then you cannot have the code clean of warnings using cppformat. Looking forward to the new release.

**Comment by vitaut** [comment]
I've created branch https://github.com/cppformat/cppformat/tree/2.x for the new release. The changes (mostly CMake update) are described in the [changelog](https://github.com/cppformat/cppformat/blob/2.x/ChangeLog.rst#201---tbd). AFAICS the code compiles cleanly with clang. This will be a minor release because I haven't included any changes to the main API which will have to wait till the next major one. Let me know if you want to see anything else in this release.

**Comment by WscriChy** [comment]
Seems it is working fine. Thank you. I am waiting for a tag to submit package.

**Comment by vitaut** [comment]
Done: https://github.com/cppformat/cppformat/releases/tag/2.0.1
