### ISSUE TITLE
Compile time checking of format string?

### ISSUE THREAD

**Issue by paulsapps** [cppformat/cppformat#295]
Would it be possible to add this feature using constexpr compile time format string checking? For example:

fmt::format("{} {}", "blah");

Would result in compile time instead of run time error..

**Comment by nabijaczleweli** [comment]
No, TTBOMK, because one can't pass string literals as template arguments, so compile-time string inspection is well-nigh impossible.

**Comment by vitaut** [comment]
Unfortunately it is not possible (at least with a usable API) at the moment because of the difficulties of handling string literals that @nabijaczleweli mentioned.

However, you can get compile-time checking of `printf`-style format strings (but not Python-like format strings) as described in https://github.com/cppformat/cppformat/issues/62#issuecomment-77490707.

**Comment by vitaut** [comment]
Compile-time format string checks are now available: http://zverovich.net/2017/11/05/compile-time-format-strings.html

**Comment by mattgodbolt** [comment]
For those like me coming here from Google and finding that linked site is down, the main [README](https://github.com/fmtlib/fmt/blob/master/README.rst) has this example:

```cpp
std::string s = fmt::format(FMT_STRING("{:d}"), "don't panic");
```

**Comment by vitaut** [comment]
There are also docs for the most adventurous people: https://fmt.dev/latest/api.html#compile-api
