### ISSUE TITLE
format.cc (in header only mode) includes windows.h without defining WIN32_LEAN_AND_MEAN

### ISSUE THREAD

**Issue by gabime** [cppformat/cppformat#297]
and this for example [breaks](https://github.com/gabime/spdlog/issues/179#issuecomment-199079702) boost and other libs

**Comment by vitaut** [comment]
I don't think it's a good idea to define `WIN32_LEAN_AND_MEAN` there because it may break users who include `windows.h` without this macro and use these rare features. There are two alternative solutions:

1. Define `FMT_USE_WINDOWS_H` to 0 if you don't need Windows error reporting functionality and Unicode converters provided by C++ Format.
2. Define `WIN32_LEAN_AND_MEAN` yourself if you are OK with potential issues.

This can be done in the same place where you define `FMT_HEADER_ONLY`.

**Comment by gabime** [comment]
In this case I might defineFMT_USE_WINDOWS_H to 0 in spdlog..

 What is the Windows error reporting functionality?

**Comment by vitaut** [comment]
It's [WindowsError](http://cppformat.github.io/latest/api.html#_CPPv2N3fmt12WindowsErrorE) exception and `report_windows_error` function that automatically translate the error code returned by `GetLastError()` into a text message. The formatting functions don't use this, so if you don't use this either, spdlog won't be affected.
