### ISSUE TITLE
Precision specifier for non-number arguments

### ISSUE THREAD

**Issue by lahwaacz** [cppformat/cppformat#90]
From [the docs](http://cppformat.readthedocs.org/en/latest/syntax.html#formatspec):

<blockquote>The precision is a decimal number indicating how many digits should be displayed after the decimal point for a floating-point value formatted with 'f' and 'F', or before and after the decimal point for a floating-point value formatted with 'g' or 'G'. For non-number types the field indicates the maximum field size - in other words, how many characters will be used from the field content. The precision is not allowed for integer values.</blockquote>

So I tried to use precision on a string argument, for example:

```
std::cout << fmt::format("{0:.2s}", "test") << std::endl;
```
which results in segfault:
```
terminate called after throwing an instance of 'fmt::FormatError'
  what():  precision specifier requires floating-point argument
Aborted (core dumped)
```

Also note that [printf](http://en.cppreference.com/w/cpp/io/c/fprintf) allows the precision specifier even for integer arguments:

<blockquote>Precision specifies the minimum number of digits to appear.</blockquote>

**Comment by vitaut** [comment]
Good catch, I'll have a look into this. Thanks!

**Comment by vitaut** [comment]
Fixed in https://github.com/cppformat/cppformat/commit/43aebf51d60bc57b5d70d9097d0109300243e225. As for "precision" for integer arguments, the `fmt::format` function follows Python's conventions in not allowing it, but as in Python you can use a combination of fill and width for similar effect:

```
fmt::format("{:05}", 42); // returns "00042"
```
or use `fmt::sprintf` which follows `printf` conventions and allows precision for integer arguments.

**Comment by lahwaacz** [comment]
Thanks, I was not aware of Python's approach so in that case everything is all right...
